name: caretaker_wellnest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.4
  intl: ^0.20.2
  flutter_holo_date_picker: ^2.0.0
  flutter_local_notifications: ^19.0.0
  timezone: ^0.10.0
  permission_handler: ^11.4.0
  google_fonts: ^6.2.1
  lottie: ^3.3.1
  android_alarm_manager_plus: ^4.0.7
  device_info_plus: ^11.3.0
  flutter_timezone: ^4.1.0
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  googleapis_auth: ^2.0.0
  http: ^1.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - asset/
