name: admin_wellnest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  supabase_flutter: ^2.8.3
  image_picker: ^1.1.2
  file_picker: ^9.0.0
  fl_chart: ^0.70.2
  intl: ^0.20.2
  url_launcher: ^6.3.1
  pdf: ^3.11.3
  printing: ^5.14.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - asset/
